# 应用配置
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/his02?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Ollama4j 配置
ollama:
  base-url: http://localhost:11434
  model: deepseek-r1:7b
  timeout: 60000


aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: sky-take-out039
    region: cn-hangzhou

# 百炼云部署配置
# 百炼云部署配置
bailian:
  api-key: ${DASHSCOPE_API_KEY}
  base-url:  https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
  model: qwen-turbo

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: DelMark
      logic-delete-value: 0
      logic-not-delete-value: 1
  # 添加这两个配置项到 mybatis-plus 节点下
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neuedu.hisweb.entity

# 日志配置
logging:
  level:
    web: debug
    com.neuedu.his.dao: debug

# 密钥配置
#secretkey: hisweb
jwt:
  secretkey: hisweb  # 应用级别的密钥，用于额外安全验证
  expireTime: 3600                # JWT过期时间（秒），默认值为1年(31536000)